### ISSUE TITLE
Vertaisarviointi #1

### ISSUE THREAD

**Issue by pants64DS** [lxhelmer/tiralabra#1]
Projekti ladattu 19.2. klo 19.52.

En pystynyt suorittamaan ohjelmaa, koska minulta puuttui tarvittavat CSV-tiedostot. Sain kuitenkin ladattua muut tiedostot MNIST:in sivuilta. Yksikkötestejä ei näytä olevan, mutta vaikuttaa siltä että itse ohjelman suorittaminen testaa sitä kokonaisuudessaan.

Vaikka koodissa ei olekaan paljoa kommentteja, sitä on silti kohtuullisen helppo ymmärtää. Ohjelman toiminta vaikuttaa järkevältä, vaikka en tiedäkään aiheesta kovin paljoa. En nää myöskään ohjelman tehokkuudessa juurikaan parannettaavaa, ainakaan ilman että käytettyjä algoritmeja muutetaan merkittävästi.

Vielä muutama huomio koodin laadusta ja muista "pikkuasioista":

* `etaisyys_a_b`-funktiossa itseisarvo on turha, koska `math.sqrt` ei koskaan palauta negatiivista lukua. Suosittelisin kuitenkin käyttämään `math.hypot`-funktiota etäisyyden laskemiseen.
* Pylint antaa jonkin verran "trailing whitespace" -virheitä. Nämä on varmasti helppo korjata.
* `main.py`-tiedostossa on jonkin verran tavaraa, joka voisi olla muissa tiedostoissa.
* Koodin seassa on joitakin pois kommentoituja kohtia, mutta tämä on varmaan tässä vaiheessa vielä OK.
* `(1/len(joukko_A)) * summa` voisi varmaan olla vain `summa/len(joukko_A)`?
* `reuna`-funktion voisi kirjoittaa yhdellä `return`-käskyllä seuraavasti:
```python
def reuna(mnistkuva,y,x):
    return y == 0 or y == 27 or x == 0 or x == 27 \
        or mnistkuva[y-1, x-1] == 0 \
        or mnistkuva[y-1, x  ] == 0 \
        or mnistkuva[y-1, x+1] == 0 \
        or mnistkuva[y,   x-1] == 0 \
        or mnistkuva[y,   x+1] == 0 \
        or mnistkuva[y+1, x-1] == 0 \
        or mnistkuva[y+1, x  ] == 0 \
        or mnistkuva[y+1, x+1] == 0
```
On kuitenkin makuasia, kumpi on parempi.

**Comment by lxhelmer** [comment]
Ohjelma pystyy generoimaan vaadittavat csv:t itse. Tosin tämä toiminnallisuus odottaa siirtoa omaan luokkaansa main.py stä. Kiitos rakentavasta palautteesta :)
